@echo off
echo Parando containers...
docker-compose down

echo Removendo imagens antigas...
docker rmi tecsim-web tecsim-mobile tecsim-backend 2>nul

echo Limpando cache do Docker...
docker system prune -f

echo Reconstruindo containers do zero...
docker-compose build --no-cache

echo Iniciando containers...
docker-compose up